version: '3'

services:
  projectmanagementweb:
    image: webapplication
    build:
      context: .
      dockerfile: WebApplication/Dockerfile
  projectmanagementapi:
    image: projectmanagementapi
    build:
      context: .
      dockerfile: ProjectManagement/Dockerfile
  identityserver:
    image: identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
  mssqldb:
    image: "microsoft/mssql-server-linux"