version: '3'

services:
  projectmanagementapi:
    image: projectmanagementapi
    build:
      context: .
      dockerfile: ProjectManagement/Dockerfile
  projectmanagementdb:
    image: "microsoft/mssql-server-linux"
  webapplication:
    image: webapplication
    build:
      context: .
      dockerfile: WebApplication/Dockerfile