version: '3'

services:
  projectmanagementapi:
    image: projectmanagementapi
    build:
      context: .
      dockerfile: ProjectManagement/Dockerfile
  projectmanagementweb:
    image: projectmanagementweb
    build:
      context: .
      dockerfile: WebApplication/Dockerfile
  projectmanagementdb:
    image: "microsoft/mssql-server-linux"