version: '3'

services:
  projectmanagementapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:9000"
  projectmanagementweb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  projectmanagementdb:
    environment:
      - SA_PASSWORD=48hEw5bDHSjfpSta
      - ACCEPT_EULA=Y